[package]
name = "audio_set_sink"
version = "0.1.0"
authors = ["Edvin Hultberg <hultberg@mittnett.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
